#!/bin/sh

PNAME=RJDBC
SWD=`pwd`
echo "Removing previous dist ..."
rm -rf /tmp/${PNAME}
echo "Copying package base ..."
cp -r ../${PNAME} /tmp

cd /tmp/${PNAME}

echo "Removing CVS and backup stuff ..."
find . -name CVS -o -name .svn | xargs rm -rf
find . -name \*~ | xargs rm -f

mkdir -p inst/java
javac -d inst/java -source 1.4 -target 1.4 java/*.java || exit 1
(cd inst/java; jar fvc RJDBC.jar info; rm -rf info)

echo "Updating version ..."
VER=`./version`
echo "$PNAME version ${VER}"
#cat DESCRIPTION| sed "s/Version:.*/Version: ${VER}/" > d
#mv d DESCRIPTION

rm -f "/tmp/${PNAME}/mkdist" "/tmp/${PNAME}/version" "/tmp/${PNAME}/test.sh"

echo "Creating package ..."
cd ..
R CMD build "${PNAME}"
cd ${SWD}
cp /tmp/${PNAME}_${VER}.tar.gz ..
rm -rf /tmp/${PNAME}
echo "Done."
ls -l ../${PNAME}_${VER}.tar.gz
