on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: check

jobs:
  check:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} (${{ matrix.r }})

    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-2022', 'macOS-10.15', 'ubuntu-20.04' ]
        r:  [ 'release' ]
        java: [ 8, 11 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install R
        uses: s-u/R-actions/install@v1
        with:
          r-version: ${{ matrix.r }}
          tools: base

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build
        run: "sh mkdist"

      - name: Info
        run: "bash -c 'java -version && which java && echo $PATH && echo $JAVA_HOME'"

      - name: Setup R Java support
        if: runner.os != 'Windows'
        run: "echo export PATH=$PATH > reconf.sh; echo export JAVA_HOME=$JAVA_HOME >> reconf.sh; echo R CMD javareconf >> reconf.sh; sudo bash reconf.sh"

      - name: Install rJava
        run: "Rscript -e 'install.packages(as.character(c(quote(DBI), quote(rJava))))'"

      - uses: s-u/R-actions/pkg-check@v1
